version: '2.4'
services:
  postgres:
    container_name: postgres
    image: 'toddhow/postgres:main'
    networks:
      pyne:
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

volumes:
  postgres-data:
    external: true

networks:
  pyne: