version: '2.4'
services:
  postgres:
    container_name: postgres
    image: 'pyne/postgres:latest'
    networks:
      pyne:
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  pyne:
    build:
      context: ../
    container_name: pyne
    links:
      - postgres
    depends_on:
      - postgres
    env_file:
      - ../.env
    image: 'pyne/bot:latest'
    networks:
      pyne:
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true
    command: 'yarn db:prod'

volumes:
  postgres-data:
    external: true

networks:
  pyne: