name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@v2
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restore CI Cache
        uses: actions/cache@v2.1.6
        id: cache-restore
        with:
          path: node_modules
          key: ${{ runner.os }}-16-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: pnpm ci
      - name: Run Prettier
        run: pnpm run format
