name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # renovate: tag=v2
      - name: Use Node.js v16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # renovate: tag=v2
        with:
          node-version: 16
      - name: Cache .pnpm-store
        uses: actions/cache@70655ec8323daeeaa7ef06d7c56e1b9191396cbe # renovate: tag=v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
      - name: Setup PNPM
        uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2 # renovate: tag=v2.0.1
        with:
          version: 6.0.2
      - name: pnpm Build
        run: pnpm install
      - name: Run Prettier
        run: pnpm run format
